%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/angel/Documents/UPC-MASTER/robot-learning/quadruped-robot/trained_models/quadruped_robot_err_vel_DDPG_1A_4/auxiliar/EpisodeRewards.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2019/01/16 10:35:05

%% Initialize variables.
% filename = 'EpisodeRewards.txt';
% filename = 'EpisodeLengths.txt';
filename = 'AccLengths.txt';
delimiter = {''};
formatSpec = '%f%[^\n\r]';
% formatSpec = '%f%f%[^\n\r]';

fileID = fopen(filename,'r');
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string',  'ReturnOnError', false);
fclose(fileID);
% EpisodeRewards2 = [dataArray{1:end-1}];
% EpisodeLengths2  = [dataArray{1:end-1}];
AccLengths2  = [dataArray{1:end-1}];
% EpisodeLengths = [dataArray{1},dataArray{2}]
%%
EpisodeRewards = [EpisodeRewards1;EpisodeRewards2]
EpisodeLengths = [EpisodeLengths1;EpisodeLengths2]
AccLengths = [AccLengths1;AccLengths1(end)+AccLengths2]
figure (1)
subplot(3,1,1);
plot(EpisodeRewards)
ylabel('Episode Reward');
xlabel('Steps (thousands)');
title('Episode Reward over Steps');
grid on;
% figure (2)
subplot(3,1,2);
plot(AccLengths,EpisodeRewards)
ylabel('Episode Reward');
xlabel('Time (seconds)');
title('Episode Reward over Time');
grid on;
% figure (3)
subplot(3,1,3);
plot(EpisodeLengths)
ylabel('Episode Length');
xlabel('Steps (thousands)');
title('Episode Length over Steps');
grid on;
% plot(TimeRewards(2,:),TimeRewards(1,:))
